builds:
  - goos:
      - darwin
      - windows
      - linux
      - freebsd
    env:
      - CGO_ENABLED=0
    ldflags: -s -w -X github.com/jckuester/terradozer/internal.version={{.Version}} -X github.com/jckuester/terradozer/internal.commit={{.ShortCommit}} -X github.com/jckuester/terradozer/internal.date={{.Date}}

archives:
  - format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
